### ISSUE TITLE
Футер выходит за пределы контеинера по ширине

### ISSUE THREAD

**Issue by dmitriy-baltak** [vanok1993/vanok1993.github.io#12]
http://joxi.ru/Drlan1QUYwl9mP

**Comment by molodshiy** [comment]
Зробив. Чи обовяково потрібно переносити футер в контейнер?

**Comment by dmitriy-baltak** [comment]
Обычно да футер ложат в контейнер, но есть исключения, например когда нам необходимо реализовать футер прибитый к низу экрана или когда дизайн этого явно не подразумевает, но в большинстве случаев он в контеинере.
