### ISSUE TITLE
L4: Заменить либо на картинку либо на иконочный шрифт

### ISSUE THREAD

**Issue by dmitriy-baltak** [vanok1993/vanok1993.github.io#15]
http://joxi.ru/xAeGdR1f3kwzmy

**Comment by molodshiy** [comment]
Замінив на іконочний шрифт. В файлі fontello.css є закомічений стиль  /\*  speak: none;*/ він створює error, в чому проблема?

**Comment by dmitriy-baltak** [comment]
Не совсем понял вопрос, что за стиль и какую ошибку он генерирует

**Comment by molodshiy** [comment]
В файлі fontello.css є закомічений стиль /\* speak: none;*/ він створює error, в чому проблема?
http://joxi.ru/D2PDv7DSdjOxV2
По дефолту він не закомічений но тоді він строрює error.

**Comment by dmitriy-baltak** [comment]
А где именно ошибка появляется? Вообще это новый стиль который запрещает голосовое воспроизведение

**Comment by molodshiy** [comment]
Зрозумів.
