### ISSUE TITLE
Необходимо контенту задать отступы справа и слева на ширину правой и левой колонок

### ISSUE THREAD

**Issue by dmitriy-baltak** [vanok1993/vanok1993.github.io#18]
http://joxi.ru/VrwoO6qupP18rX

**Comment by molodshiy** [comment]
Зробив. Підкажіть будь ласка, чи є якість альтернативні методи вирішення даного питання?

**Comment by dmitriy-baltak** [comment]
Да, можно было сделать 3 колонки другим методом:
всем трем колонкам
указать float:left
задать ширину
расположить по порядку
Тогда отступы не понадобятся. Оба способа работают и используются.
