### ISSUE TITLE
Не забывайте указывать top, left/right, bottom если вы указываете position: absolute.

### ISSUE THREAD

**Issue by dmitriy-baltak** [vanok1993/vanok1993.github.io#20]
http://joxi.ru/8AnXv76fbKBMmO

**Comment by molodshiy** [comment]
Зробив. Потрібно вказувати два параметри чи всі?

**Comment by dmitriy-baltak** [comment]
Нужно только 2, если указываете все 4 и при этом не указываете высоту и ширину то елемент будет соответсвенно растянут на всю ширину высоту экрана вплоть до указанных 4 отступов
