### ISSUE TITLE
L11: Убрать конструкцию new Array(i)

### ISSUE THREAD

**Issue by dmitriy-baltak** [vanok1993/vanok1993.github.io#27]
var i = 5;
var arr = new Array(i);

Старайся не использовать такое объявление массива, это считается плохой практикой, вместо этого постаточно объявить пустой массив так:
var arr = [];

В этом случае и цикл сбора имен будет выглядеть иначе, проще:
for(var j = 0; j < 5; j++){
    arr.push(prompt("Enter Name", "Name"));
}

**Comment by molodshiy** [comment]
Зробив.
