### ISSUE TITLE
L5-6: Кнопки старт и пауза

### ISSUE THREAD

**Issue by dmitriy-baltak** [vanok1993/vanok1993.github.io#38]
Гораздо проще будет если ты сделаешь что бы это было 2 разные кнопки со своими обработчиками, чем если будешь менять обработчик и содержимое у одной

**Comment by molodshiy** [comment]
Зробив дві окремі кнопки, 1-старт і 2-(пауза-продовжити). Но на кнопці 2-(пауза-продовжити), все рівно приходиться міняти оброботчики. Їх теж потрібно розділити?
І чи є альтернативні методи з тим шоб на одній кнопці не міняти оброботчики, но мінялись і значення(назва) і її властивості при кліку на них?
