### ISSUE TITLE
Убрать класс padding_left

### ISSUE THREAD

**Issue by dmitriy-baltak** [vanok1993/vanok1993.github.io#4]
Старайтесь не задавать настолько специфичные классы, в данном случае будет можно задать класс my_feedback и ему установить нужный падинг

**Comment by molodshiy** [comment]
Якщо клас padding_left не потрібний то під цю ж логіку попадає і border_bottom, його теж видаляти? Чи padding_left удалити тільки для останього div-а?

**Comment by dmitriy-baltak** [comment]
border_bottom можно оставить, но переименовать на более общее название, типа about_block, таким образом если в дальнейшем заказчик попросит добавить для этих блоков какое то еще оформление это будет достаточно просто сделать добавив стили в этот класс
padding_left лучше убрать потому что это стиль который задает фиксированный отступ с одной стороны, он слишком узко специализированный, нужно стараться делать верстку более гибкой, т.к. в реальном макете у нас будет огромное кол-во блоков и если для каждого падинга мы будем создавать свой класс, верстка в какой то момент станет не поддерживаемой.

**Comment by dmitriy-baltak** [comment]
margin_top_none аналогично padding_left
