### ISSUE TITLE
L7-8: Используй кеширование елементов

### ISSUE THREAD

**Issue by dmitriy-baltak** [vanok1993/vanok1993.github.io#43]
http://joxi.ru/LmGVxdEsR5wZWr
Тут происходит поиск по всему ДОМ дереву каждый раз заново, используй кеширование
var $someVar = $('.some-list');

$someVar.find('.active-element').removeClass('active-element');
$someVar.find(....).addClass('active-element');

при этом у active-element в стилях должно быть прописано display block, а у остальных елементов по умолчанию display none

также вместо нативного className нужно использовать аналог из jq

**Comment by molodshiy** [comment]
Зробив.
